### PR TITLE
Replace plupload with uppy

### PR DESCRIPTION
**Pull request by DreamlandOwO**
So what I did is I replaced Plupload with Uppy.

Plupload is okay but it doesn't upload multiple files at same time. Both are in simliar download size, so that's good. Uppy supports more ways to upload your files, even from a [webcam](https://uppy.io/docs/webcam/) if we really want that 😂.

Added drag'n'drop to upload modal, if we can just add that to explorer it would be even better.

Upload performance is noticeable better than plupload when there's a lot of files in queue, thanks to Uppy XHR plugin's parallel upload support. Currently I hard-coded parallels limit to 5, maybe we can expose this param to user.

Also some additional tweaks, like:

- Limit LazyLoad only apply for selectorArea instead of whole document.
- Added scrollbar to file list on some modal, so it would not expand to the entire page (I tired select over 30 files and delete them, that file list was so long, it blocks the confirm button).
- Added some preview files so newcomer can just run `npm run dev` to get things to start.
- Two new locales, but we need update other locales except English and Chinese.
- Right way (I think) to filter out external dependencies, so the whole thing would be smaller.

### CODE REVIEW

**Comment by n1crack** [comment]
Nice one, thanks. I was also planning to replace plupload, but couldn't decide which one to replace with. 

I'll check the code asap and merge it. 

Thanks for the contribution.

**Comment by n1crack** [comment]
I made some changes, I would be happy if you check it.

- I think there is no rush for the missing fields in the languages, the relevant people will add them anyway.
- fixed hebrew shortcode in dropdown.
- tw preflight mode is turned on again. 
- border color added to the select element in the status bar

**Comment by DreamlandOwO** [comment]
Fixed upload clear only successful button, I changed too many times forgot that still broken xD.

One issue with firefox, the <select> by default have a gray background under it, but chrome doesn't have, but yea I mean is firefox we can leave as is.

Chrome:
image

Firefox:
image

Rest looks good to me.

**Comment by n1crack** [comment]
Can you check the error messages ? Is this how supposed to be ?

image

**Comment by DreamlandOwO** [comment]
Yea is kinda dumb show entire message from the server response on the file status, but other issue I encountered is if I try put them into the below messagebox it would be super long, should I just make message box scrollable and file status as simple `[Error]`?

**Comment by n1crack** [comment]
Nop its all good, There 2 issues im looking right now.

1. dark mode colors.
2. localization import for uppy :) (we can match the lang keys with uppy.)

image

**Comment by DreamlandOwO** [comment]
So I made some changes now it looks better on dark mode.

Tailwind for me is very painful deal with, is this the way future devs gonna really writing this for now, back in before CSS is thing? I add some line breaks on class so I can actually knowing which part is which, we should extract them as [@apply](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply) or components, otherwise this is hell to maintain.

Currently looks like this on upload modal, should apply for other stuff:

image

I did [dynamic import uppy locales](https://github.com/n1crack/vuefinder/pull/30/commits/eeda55fa0ef9cbdf184bfb01e7dc7fc49d03f749#diff-0ddff6cdcb23b9a22d55b9706c36478f97bd2cd3d54ba2de8b1de56495a90582R344) but it just give me tons unused files on build, we need figure out a better way to do this.

image

**Comment by n1crack** [comment]
updated localization can you check it..
- changed json files to js.
- we can use uppy's translations for some of the files. I left an example in the ModalUpload

**Comment by DreamlandOwO** [comment]
Oh yea just import uppy locale from our locale is definitely better, we should do that

**Comment by n1crack** [comment]
we have a merge conflict :)

**Comment by DreamlandOwO** [comment]
I saw that, let me just handle that right now

**Comment by n1crack** [comment]
already cleaned up. :)

**Comment by DreamlandOwO** [comment]
Nice!

**Comment by n1crack** [comment]
> Tailwind for me is very painful deal with, is this the way future devs gonna really writing this for now, back in before CSS is thing? I add some line breaks on class so I can actually knowing which part is which, we should extract them as @apply or components, otherwise this is hell to maintain.

I missed this part, yes with this It is very hard to maintain. But when you feel comfortable, you barely need to touch css files again. And you get the things done in just a second. 

There are 2 options to simplify it, first one is to use @apply, the other one is to break everything to components like in React. 

I think, we should go for using @apply.

**Comment by n1crack** [comment]
With a very long names and on small screens, the list wasn't looking well. have made some changes : 

image

image

**Comment by DreamlandOwO** [comment]
Yea we can go for`@apply`, thx for the merge!

**Comment by n1crack** [comment]
demo in the vuefinder.ozdemir.be is updated. 
- we should move all upload logic to its own js file.
- There is a 10MB upload limit in the demo page, it doesn't show that error. (maybe I commented the message component, thats why)

otherwise it seems all good. thanks again.

**Comment by n1crack** [comment]
https://www.youtube.com/watch?v=Gd5lmAb4Iqw

I'll leave this here. It will help to simplify things later.

**Comment by DreamlandOwO** [comment]
Thank you, I look up later.

**Comment by DreamlandOwO** [comment]
It will work, that ref is separated by current component instance, "root" as just a name. Unless you manually use `inject` that ref (as I did declare with `provide`), other component can give whatever vnode ref name as root, as long as haven't use that name in the same component before.

**Comment by n1crack** [comment]
Yea thats right. Im using vue2 and other libraries with my other projects, and confused a bit. yea its all good :) no worries.

**Pull request merged**
